In [1]:
import numpy as np
Day_number=np.arange(1,11)
Steps_walked=[6012,7079,6886,7230,4598,5564,6971,7763,8032,9569]
arr=np.array([Day_number,Steps_walked])
arr=arr.T
arr

array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])

In [3]:
new_arr=arr[:,1]+2000
arr[:,1]=new_arr
arr

array([[    1, 10012],
       [    2, 11079],
       [    3, 10886],
       [    4, 11230],
       [    5,  8598],
       [    6,  9564],
       [    7, 10971],
       [    8, 11763],
       [    9, 12032],
       [   10, 13569]])

In [4]:
matched=arr[:,1]>9000
matched
new_arr=arr[matched]
new_arr

array([[    1, 10012],
       [    2, 11079],
       [    3, 10886],
       [    4, 11230],
       [    6,  9564],
       [    7, 10971],
       [    8, 11763],
       [    9, 12032],
       [   10, 13569]])

In [5]:
SortedArr=arr[arr[:1].argsort()]
print('sorted 2D numpy array')
print(SortedArr)

sorted 2D numpy array
[[[    1 10012]
  [    2 11079]]]


In [6]:
import pandas as pd
import numpy as np
marks={'chemistry':[67,90,66,32],
      'physics':[45,92,72,40],
      'mathematics':[50,87,81,12],
      'english':[19,90,72,68]}
marks_df=pd.DataFrame(marks,index=['subodh','ram','abdul','john'])
marks_df

chemistry  physics  mathematics  english
subodh         67       45           50       19
ram            90       92           87       90
abdul          66       72           81       72
john           32       40           12       68

In [7]:
marks_df['total']=marks_df['chemistry']+marks_df['physics']+marks_df['mathematics']+marks_df['english']
marks_df

chemistry  physics  mathematics  english  total
subodh         67       45           50       19    181
ram            90       92           87       90    359
abdul          66       72           81       72    291
john           32       40           12       68    152

In [9]:
marks_df.drop(columns='total',inplace=True)
marks_df

chemistry  physics  mathematics  english
subodh         67       45           50       19
ram            90       92           87       90
abdul          66       72           81       72
john           32       40           12       68

In [10]:
new_marks=marks_df+5
new_marks

chemistry  physics  mathematics  english
subodh         72       50           55       24
ram            95       97           92       95
abdul          71       77           86       77
john           37       45           17       73

In [12]:
new_marks=marks_df+[5,10,10,2]
new_marks

chemistry  physics  mathematics  english
subodh         72       55           60       21
ram            95      102           97       92
abdul          71       82           91       74
john           37       50           22       70

In [13]:
marks_df.apply(np.sum,axis=1)
marks_df

chemistry  physics  mathematics  english
subodh         67       45           50       19
ram            90       92           87       90
abdul          66       72           81       72
john           32       40           12       68

In [15]:
f=marks_df<35
marks_df.mask(f,'Fail')
marks_df

chemistry  physics  mathematics  english
subodh         67       45           50       19
ram            90       92           87       90
abdul          66       72           81       72
john           32       40           12       68

In [17]:
import numpy as np
import pandas as pd
df=pd.read_csv('C:/Users/Admin/Desktop/kavya/autompg1627540133031.csv')
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [18]:
df.loc[(df['acceleration']>17)&(df['weight']<2223)]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
19   26.0          4          97.0        46.0    1835          20.5   
32   25.0          4          98.0         NaN    2046          19.0   
51   30.0          4          79.0        70.0    2074          19.5   
53   31.0          4          71.0        65.0    1773          19.0   
54   35.0          4          72.0        69.0    1613          18.0   
55   27.0          4          97.0        60.0    1834          19.0   
56   26.0          4          91.0        70.0    1955          20.5   
79   26.0          4          96.0        69.0    2189          18.0   
102  26.0          4          97.0        46.0    1950          21.0   
117  29.0          4          68.0        49.0    1867          19.5   
129  31.0          4          79.0        67.0    1950          19.0   
131  32.0          4          71.0        65.0    1836          21.0   
145  32.0          4          83.0        61.0    2003          19.0   
181  33.0          4          91.0        53.0    1795          17.5   
195  29.0          4          85.0        52.0    2035          22.2   
196  24.5          4          98.0        60.0    2164          22.1   
198  33.0          4          91.0        53.0    1795          17.4   
216  31.5          4          98.0        68.0    2045          18.5   
218  36.0          4          79.0        58.0    1825          18.6   
244  43.1          4          90.0        48.0    1985          21.5   
246  32.8          4          78.0        52.0    1985          19.4   
247  39.4          4          85.0        70.0    2070          18.6   
303  31.8          4          85.0        65.0    2020          19.2   
310  38.1          4          89.0        60.0    1968          18.8   
322  46.6          4          86.0        65.0    2110          17.9   
324  40.8          4          85.0        65.0    2110          19.2   
325  44.3          4          90.0        48.0    2085          21.7   
330  40.9          4          85.0         NaN    1835          17.3   
331  33.8          4          97.0        67.0    2145          18.0   
346  32.3          4          97.0        67.0    2065          17.8   
347  37.0          4          85.0        65.0    1975          19.4   
348  37.7          4          89.0        62.0    2050          17.3   
376  37.0          4          91.0        68.0    2025          18.2   
377  31.0          4          91.0        68.0    1970          17.6   
379  36.0          4          98.0        70.0    2125          17.3   
394  44.0          4          97.0        52.0    2130          24.6   

     model_year  origin                             name  
19           70  europe     volkswagen 1131 deluxe sedan  
32           71     usa                       ford pinto  
51           71  europe                      peugeot 304  
53           71   japan              toyota corolla 1200  
54           71   japan                      datsun 1200  
55           71  europe             volkswagen model 111  
56           71     usa                 plymouth cricket  
79           72  europe                  renault 12 (sw)  
102          73  europe          volkswagen super beetle  
117          73  europe                         fiat 128  
129          74   japan                      datsun b210  
131          74   japan              toyota corolla 1200  
145          74   japan                       datsun 710  
181          75   japan                 honda civic cvcc  
195          76     usa               chevrolet chevette  
196          76     usa                  chevrolet woody  
198          76   japan                      honda civic  
216          77   japan                honda accord cvcc  
218          77  europe                    renault 5 gtl  
244          78  europe  volkswagen rabbit custom diesel  
246          78   japan                 mazda glc deluxe  
247          78   japan                   d

In [19]:
df.sort_values(by='cylinders')


mpg  cylinders  displacement  horsepower  weight  acceleration  \
111  18.0          3          70.0        90.0    2124          13.5   
71   19.0          3          70.0        97.0    2330          13.5   
334  23.7          3          70.0       100.0    2420          12.5   
243  21.5          3          80.0       110.0    2720          13.5   
267  27.5          4         134.0        95.0    2560          14.2   
..    ...        ...           ...         ...     ...           ...   
86   14.0          8         304.0       150.0    3672          11.5   
285  17.0          8         305.0       130.0    3840          15.4   
286  17.6          8         302.0       129.0    3725          13.4   
92   13.0          8         351.0       158.0    4363          13.0   
0    18.0          8         307.0       130.0    3504          12.0   

     model_year origin                       name  
111          73  japan                  maxda rx3  
71           72  japan            mazda rx2 coupe  
334          80  japan              mazda rx-7 gs  
243          77  japan                 mazda rx-4  
267          78  japan              toyota corona  
..          ...    ...                        ...  
86           73    usa                amc matador  
285          79    usa  chevrolet caprice classic  
286          79    usa            ford ltd landau  
92           73    usa                   ford ltd  
0            70    usa  chevrolet chevelle malibu  

[398 rows x 9 columns]

In [20]:
df.sort_values(['acceleration','horsepower'],
              ascending=(1,0))

mpg  cylinders  displacement  horsepower  weight  acceleration  \
11   14.0          8         340.0       160.0    3609           8.0   
7    14.0          8         440.0       215.0    4312           8.5   
9    15.0          8         390.0       190.0    3850           8.5   
6    14.0          8         454.0       220.0    4354           9.0   
116  16.0          8         400.0       230.0    4278           9.5   
..    ...        ...           ...         ...     ...           ...   
195  29.0          4          85.0        52.0    2035          22.2   
59   23.0          4          97.0        54.0    2254          23.5   
326  43.4          4          90.0        48.0    2335          23.7   
394  44.0          4          97.0        52.0    2130          24.6   
299  27.2          4         141.0        71.0    3190          24.8   

     model_year  origin                name  
11           70     usa  plymouth 'cuda 340  
7            70     usa   plymouth fury iii  
9            70     usa  amc ambassador dpl  
6            70     usa    chevrolet impala  
116          73     usa  pontiac grand prix  
..          ...     ...                 ...  
195          76     usa  chevrolet chevette  
59           72  europe   volkswagen type 3  
326          80  europe  vw dasher (diesel)  
394          82  europe           vw pickup  
299          79  europe         peugeot 504  

[398 rows x 9 columns]

In [21]:
list1=[col for col in df.columns if df[col].dtype in ['float','int 64']]
df[list].agg(['min','max','sum','mean','median'])

C:\Users\Admin\AppData\Local\Temp\ipykernel_5720\2197223469.py:2: FutureWarning: ['origin', 'name'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df[list].agg(['min','max','sum','mean','median'])


mpg    cylinders  displacement    horsepower        weight  \
min        9.000000     3.000000     68.000000     46.000000  1.613000e+03   
max       46.600000     8.000000    455.000000    230.000000  5.140000e+03   
sum     9358.800000  2171.000000  76983.500000  40952.000000  1.182229e+06   
mean      23.514573     5.454774    193.425879    104.469388  2.970425e+03   
median    23.000000     4.000000    148.500000     93.500000  2.803500e+03   

        acceleration   model_year  \
min          8.00000     70.00000   
max         24.80000     82.00000   
sum       6196.10000  30252.00000   
mean        15.56809     76.01005   
median      15.50000     76.00000   

                                                   origin  \
min                                                europe   
max                                                   usa   
sum     usausausausausausausausausausausausausausajapa...   
mean                                                  NaN   
median                                                NaN   

                                                     name  
min                               amc ambassador brougham  
max                                      vw rabbit custom  
sum     chevrolet chevelle malibubuick skylark 320plym...  
mean                                                  NaN  
median                                                NaN

In [22]:
df.groupby(['model_year']).count()['horspower']

KeyError: 'horspower'