In [3]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.Collecting tensorflow



In [10]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
print(tf.__version__)

2.11.0


In [12]:
# importing tensorflow
import tensorflow as tf
 
# creating nodes in computation graph
node1 = tf.constant(3, dtype=tf.int32)
node2 = tf.constant(5, dtype=tf.int32)
node3 = tf.add(node1, node2)
 
# create tensorflow session object
sess = tf.compat.v1.Session()
 
# evaluating node3 and printing the result
print("sum of node1 and node2 is :",sess.run(node3))
# closing the session
sess.close()

sum of node1 and node2 is : 8


In [21]:
# importing tensorflow
import tensorflow as tf

tf.compat.v1.disable_eager_execution()
print(tf.__version__)


# creating nodes in computation graph
node = tf.Variable(tf.zeros([2,2]))

# running computation graph
with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())

# evaluating node
    print("Tensor value before addition:\n",sess.run(node))

# elementwise addition to tensor
    node = node.assign(node + tf.ones([2,2]))
# evaluate node again
    print("Tensor value after addition:\n", sess.run(node))


2.11.0
Tensor value before addition:
 [[0. 0.]
 [0. 0.]]
Tensor value after addition:
 [[1. 1.]
 [1. 1.]]


In [24]:
# importing tensorflow
import tensorflow as tf
 
# creating nodes in computation graph
a = tf.compat.v1.placeholder(tf.int32, shape=(3,1))
b = tf.compat.v1.placeholder(tf.int32, shape=(1,3))
c = tf.matmul(a,b)
 
# running computation graph
with tf.compat.v1.Session() as sess:
    print(sess.run(c, feed_dict={a:[[3],[2],[1]], b:[[1,2,3]]}))

[[3 6 9]
 [2 4 6]
 [1 2 3]]
