In [1]:
import numpy as np
a=np.array([5,6,7])
a

array([5, 6, 7])

In [6]:
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
a.sum()

18

In [8]:
b.sum()

21.5

In [9]:
a.min()

5

In [10]:
b.min()

1.5

In [11]:
b.max(axis=1)

array([3., 6.])

In [12]:
a.max()

7

In [13]:
b.max()

6.0

In [14]:
b.max(axis=0)

array([4., 5., 6.])

In [16]:
a.max(axis=0)

7

In [20]:
a.cumsum(axis=0)

array([ 5, 11, 18], dtype=int32)

In [22]:
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [23]:
b.cumsum(axis=0)

array([[1.5, 2. , 3. ],
       [5.5, 7. , 9. ]])

In [24]:
a.mean()

6.0

In [25]:
b.mean()

3.5833333333333335

In [26]:
np.median(a)

6.0

In [27]:
np.median(b)

3.5

In [28]:
np.std(a)

0.816496580927726

In [29]:
np.std(b)

1.5920810978785667

In [44]:

a=np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [45]:
b=np.arange(5,10)
b

array([5, 6, 7, 8, 9])

In [46]:
a+b

array([ 5,  7,  9, 11, 13])

In [47]:
a=np.array([
    [0,0,0],
    [1,1,1],
    [2,2,2],
    [3,3,3],
])
a

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [48]:
a.shape

(4, 3)

In [50]:
b=np.array([[6,7,8]])
b

array([[6, 7, 8]])

In [51]:
b.shape

(1, 3)

In [52]:
a+b

array([[ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11]])

In [54]:
a=np.arange(0,6)
a

array([0, 1, 2, 3, 4, 5])

In [55]:
a+10

array([10, 11, 12, 13, 14, 15])

In [58]:
a-10

array([-10,  -9,  -8,  -7,  -6,  -5])

In [57]:
a*10

array([ 0, 10, 20, 30, 40, 50])

In [59]:
a%10

array([0, 1, 2, 3, 4, 5], dtype=int32)

In [61]:
a>2

array([False, False, False,  True,  True,  True])

In [62]:
a<4

array([ True,  True,  True,  True, False, False])

In [65]:
x=lambda x:x**2
x(9)

81

In [72]:
a=lambda x,y:x+y
a(4,5)


9

In [78]:
b=lambda x:x[0]=='a'
b('apple')

True

In [79]:
b('banana')

False

In [80]:
b=lambda x:'even' if x%2==0 else 'odd'
b(3)

'odd'

In [83]:
b=lambda x:'even' if x%2==0 else 'odd'
b(4)

'even'

In [84]:
l=[1,2,3,4,5,6,7]
l

[1, 2, 3, 4, 5, 6, 7]

In [85]:
list(map(lambda x:x*2,l))


[2, 4, 6, 8, 10, 12, 14]

In [86]:
list(map(lambda x:x%2==0,l))

[False, True, False, True, False, True, False]

In [90]:
student=[{'name':'sneha',
         'fathername':'sunil',},
         {'name':'priya',
         'fathername':'suma',}]

In [92]:
list(map(lambda student:student['name'],student))

['sneha', 'priya']

In [93]:
list(map(lambda student:student['fathername'],student))

['sunil', 'suma']

In [94]:
l=[1,2,4,5,6,8,7]
list(filter(lambda x:x>6,l))

[8, 7]

In [97]:
vegetables=('onion','potato','drumsteick','tomato')

In [99]:
list(filter(lambda vegetable:'p'in vegetable,vegetables))

['potato']

In [95]:
import functools
l1=[12,34,56,21]
l1

[12, 34, 56, 21]

In [96]:
functools.reduce(lambda x,y:x if x>y else y,l1)

56